--- #YAML:1.0
name                  : DBIx-Cache
version               : 1.0.1
abstract              : Caching for DBI handles
author:              
  - Greg Sabino Mullane <greg@endpoint.com>

license               : perl
distribution_type     : module
dynamic_config        : 1

requires:
  DBI                 : 1.52
  Digest::SHA         : 0
  perl                : 5.006001
  version             : 0
recommends:
  Cache::Memcached::Fast : 0
  Module::Signature      : 0.50
  Perl::Critic           : 0
  Test::Pod              : 0.95
  Test::Pod::Coverage    : 0
  Test::YAML::Meta       : 0.03
build_requires:
  DBI                 : 1.52
  Test::More          : 0.61
  version             : 0
configure_requires:
  DBI                 : 1.52
  version             : 0

provides:
  DBIx::Cache:
    file              : Cache.pm
    version           : 1.0.1

keywords:
  - DBI
  - cache
  - Memcached
  - Varnish

resources:
  homepage            : http://bucardo.org/dbixclass
  bugtracker          : http://bucardo.org/bugzilla/
  repository          : http://bucardo.org/dbixclass.git/
  license             : http://bucardo.org/license.html

meta-spec:
  version             : 1.3
  url                 : http://module-build.sourceforge.net/META-spec-v1.3.html

generated_by          : emacs
